#ifndef ASYNCIO_FDEVENTS_SELECT_H
#define ASYNCIO_FDEVENTS_SELECT_H

#define ASYNCIO_FDEVENTS_SELECT_READABLE	1
#define ASYNCIO_FDEVENTS_SELECT_WRITABLE	2
#define ASYNCIO_FDEVENTS_SELECT_ERRORED		4

struct asyncio_fdevents_select_evinfo {
	int events;
};

#endif
